=== Awaken-Cq/Hello-HTML/xmltest/WebContent/book.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT booklist (book)+>
	<!ELEMENT book (title, author, publisher, price, descrption?)>
	<!ATTLIST book kind (IT|소설|잡지) "IT"
					isbn ID #REQUIRED>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT author ((name|writer), tel, address)>
		<!ELEMENT name (#PCDATA)>
			<!ATTLIST name sex (남|여) "남">
		<!ELEMENT writer (#PCDATA)>
			<!ATTLIST writer sex (남|여) "남">
		<!ELEMENT tel (#PCDATA)>
		<!ELEMENT address (#PCDATA)>
	
	<!ELEMENT publisher (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ELEMENT descrption (#PCDATA)>

=== Awaken-Cq/Hello-HTML/xmltest/WebContent/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE booklist SYSTEM "book.dtd">




<booklist>
	<book kind="소설" isbn="홍8937462001">

		<title>홍길동전</title>
		<author>
			<name>허균</name>
				
			<tel>011-1234-4567</tel>
			<address>대한민국</address>
		</author>
		<publisher>민음사</publisher>
		<price>9000</price>
		</book>
	<book isbn="책8956055467">
		<title>책은도끼다</title>
		<author>
			<writer sex="여">박웅현</writer>
			<tel>010-4315-5421</tel>
			<address>대한민국</address>
		</author>
		<publisher>북하우스</publisher>
		<price>16000</price>		
	</book>	
</booklist>
